version: "3.8"
services:
  mysql-database:
    image: mysql:8.4.6
    container_name: mysql-database
    environment:
      - MYSQL_DATABASE=simple-user-api-db
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
    networks:
      - app-network
    restart: always
    ports:
      - "3307:3306"

  application:
    image: spring-app
    container_name: application
    environment:
      - MYSQL_HOST=mysql-database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_PORT=3306
    networks:
      - app-network
    depends_on:
      - mysql-database
    restart: always
    ports:
      - "8080:8080"
    build: .

networks:
  app-network: